name: tests

on: [push, pull_request]

# Cancel previous running if a new push is made
# Source: https://stackoverflow.com/a/72408109/123545
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          
          sudo apt-get install -y g++-10 make git zlib1g-dev m4
          
          # Define the compiler
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 30
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 30
          
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
          sudo update-alternatives --set cc /usr/bin/gcc
          
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
          sudo update-alternatives --set c++ /usr/bin/g++

      - name: Set up Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Build
        run: bazel build //:typesense-server

      - name: Run tests
        run: bazel test //:typesense-test

      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: typesense-server
          path: bazel-bin/typesense-server
